# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Classes/AppDelegate.h \
    ./Classes/HelloWorldScene.h \
    ./Classes/Level.h \
    ./Classes/LevelGUI.h \
    ./Classes/CCGame/include/CCACT.h \
    ./Classes/CCGame/include/CCFTG.h \
    ./Classes/CCGame/include/CCGame.h \
    ./Classes/CCGame/include/CCSTG.h \
    ./Classes/CCGame/source/CCGAnimation.h \
    ./Classes/CCGame/source/CCGCharacter.h \
    ./Classes/CCGame/source/CCGCollision.h \
    ./Classes/CCGame/source/CCGConfig.h \
    ./Classes/CCGame/source/CCGDataCache.h \
    ./Classes/CCGame/source/CCGLuaCache.h \
    ./Classes/CCGame/source/CCGLuaEngine.h \
    ./Classes/CCGame/source/CCGScene.h \
    ./Classes/CCGame/source/CCGSpell.h \
    ./Classes/CCGame/source/CCGSprite.h \
    ./Classes/CCGame/source/CCGSpriteFrame.h \
    ./Classes/CCGame/source/CCGSpriteFrameCache.h \
    ./Classes/CCGame/source/CCGVirtualJoystick.h \
    ./Classes/CCGame/source/CCPtr.h \
    ./Classes/CCGame/source/external/SneakyJoystick/SneakyButton.h \
    ./Classes/CCGame/source/external/SneakyJoystick/SneakyButtonSkinnedBase.h \
    ./Classes/CCGame/source/external/SneakyJoystick/SneakyJoystick.h \
    ./Classes/CCGame/source/external/SneakyJoystick/SneakyJoystickSkinnedBase.h \
    ./Classes/CCGame/source/frameworks/ACT/ACTCharacter.h \
    ./Classes/CCGame/source/frameworks/ACT/ACTPlayer.h \
    ./Classes/CCGame/source/frameworks/ACT/ACTRobot.h \
    ./Classes/CCGame/source/frameworks/ACT/ACTSpell.h \
    ./Classes/CCGame/source/frameworks/FTG/FTGCharacter.h \
    ./Classes/CCGame/source/frameworks/FTG/FTGPlayer.h \
    ./Classes/CCGame/source/frameworks/FTG/FTGRobot.h \
    ./Classes/CCGame/source/frameworks/FTG/FTGSpell.h \
    ./Classes/CCGame/source/frameworks/STG/STGCharacter.h \
    ./Classes/CCGame/source/frameworks/STG/STGPlayer.h \
    ./Classes/CCGame/source/frameworks/STG/STGRobot.h \
    ./Classes/CCGame/source/frameworks/STG/STGSpell.h \
    ./Classes/QtPort/CCQGLView.h \
    ./Classes/QtPort/CCQGLWidget.h \
    ./Classes/QtPort/CCQApplication.h \
    ./ccgeditor.h
SOURCES += ./ccgeditor.cpp \
    ./main.cpp \
    ./Classes/AppDelegate.cpp \
    ./Classes/HelloWorldScene.cpp \
    ./Classes/Level.cpp \
    ./Classes/LevelGUI.cpp \
    ./Classes/CCGame/source/CCGAnimation.cpp \
    ./Classes/CCGame/source/CCGCharacter.cpp \
    ./Classes/CCGame/source/CCGCollision.cpp \
    ./Classes/CCGame/source/CCGConfig.cpp \
    ./Classes/CCGame/source/CCGDataCache.cpp \
    ./Classes/CCGame/source/CCGLuaCache.cpp \
    ./Classes/CCGame/source/CCGLuaEngine.cpp \
    ./Classes/CCGame/source/CCGScene.cpp \
    ./Classes/CCGame/source/CCGSpell.cpp \
    ./Classes/CCGame/source/CCGSprite.cpp \
    ./Classes/CCGame/source/CCGSpriteFrame.cpp \
    ./Classes/CCGame/source/CCGSpriteFrameCache.cpp \
    ./Classes/CCGame/source/CCGVirtualJoystick.cpp \
    ./Classes/CCGame/source/external/SneakyJoystick/SneakyButton.cpp \
    ./Classes/CCGame/source/external/SneakyJoystick/SneakyButtonSkinnedBase.cpp \
    ./Classes/CCGame/source/external/SneakyJoystick/SneakyJoystick.cpp \
    ./Classes/CCGame/source/external/SneakyJoystick/SneakyJoystickSkinnedBase.cpp \
    ./Classes/CCGame/source/frameworks/ACT/ACTCharacter.cpp \
    ./Classes/CCGame/source/frameworks/ACT/ACTPlayer.cpp \
    ./Classes/CCGame/source/frameworks/ACT/ACTRobot.cpp \
    ./Classes/CCGame/source/frameworks/ACT/ACTSpell.cpp \
    ./Classes/CCGame/source/frameworks/FTG/FTGCharacter.cpp \
    ./Classes/CCGame/source/frameworks/FTG/FTGPlayer.cpp \
    ./Classes/CCGame/source/frameworks/FTG/FTGRobot.cpp \
    ./Classes/CCGame/source/frameworks/FTG/FTGSpell.cpp \
    ./Classes/CCGame/source/frameworks/STG/STGCharacter.cpp \
    ./Classes/CCGame/source/frameworks/STG/STGPlayer.cpp \
    ./Classes/CCGame/source/frameworks/STG/STGRobot.cpp \
    ./Classes/CCGame/source/frameworks/STG/STGSpell.cpp \
    ./Classes/QtPort/CCQApplication.cpp \
    ./Classes/QtPort/CCQGLView.cpp \
    ./Classes/QtPort/CCQGLWidget.cpp
FORMS += ./ccgeditor.ui
RESOURCES += ccgeditor.qrc
